### ISSUE TITLE
Okta Nonce Exception

### ISSUE THREAD

**Issue by mpbrooks93CAP** [okta/okta-aspnet#131] opened 2020-07-11 02:02 UTC
When logging into my ASP.NET application the user is presented with the below exception after logging in with the Okta widget which successfully goes through the entire login flow and redirects to the site with a valid token. The application uses the Okta ASP.NET middleware version 1.5.0. This error occurs after the user receives their OIDC token from the Okta authorization endpoint. We have verified that the token does contain the nonce generated by the client, and the nonce exists inside of a cookie labeled okta-oauth-nonce with SameSite = None and Security = false. It is stored at the domain (this is the same domain we are redirecting to for example portal.example.com -> portal.example.com/home/page) making the login request. It seems that the nonce stored within the cookie is somehow inaccessible to the authorization function comparing the two values, hence the error saying that it is null.

This error only occurs when we are using a custom cname on our website rather than the domain provided by our azure app service. We believe that the error is a result of the SameSite limitations from chrome release 80 (or Katana bug 197). 
This bug has been replicated in multiple environments, in chrome, in legacy edge, and in chromium based edge using .NET Framework 4.6.2 as well as .NET framework 4.8. 

We spent considerable time trying to overcome this bug including with okta engineers. We tried to force cookies to have SameSite = None and Security = True which seems to be how to allow this cookie to be shared, but the nonce cookie was unaffected. We also tried many different methods of resolving this error, and we would appreciate any help that could be provided.

We have tested these workarounds.

https://github.com/IdentityServer/IdentityServer3/issues/542#issuecomment-265421645
https://github.com/IdentityServer/IdentityServer3/issues/542
https://stackoverflow.com/questions/29502788/enabling-ssl-in-asp-net-mvc-5-app-results-in-openidconnectprotocolvalidator-issu
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/915

Please let us know if there is any additional information that we may provide.

![image](https://user-images.githubusercontent.com/68134873/87214249-f9fce580-c2f8-11ea-93a8-b507aa87b7d9.png)

## Environment

- Browser: Chrome, Legacy edge, Chromium Based Edge

- .Net Framework: .NET Framework 4.6.2 as well as .NET framework 4.8. 

- Other: Azure App Service

**Comment by bryanapellanes-okta** [comment] 2020-07-13 12:54
Hi @mpbrooks93CAP,
Thank you for submitting this issue! We will review further with the team and prioritize appropriately. We'll provide additional information here when a resolution is identified.  Stay tuned!

**Comment by mpbrooks93CAP** [comment] 2020-07-13 19:03
https://github.com/mpbrooks93CAP/Minimal-Reproduction-Bug---131

**Comment by bryanapellanes-okta** [comment] 2020-08-10 17:39
@mpbrooks93CAP ,
We were able to identify relevant information pertaining to this issue, which you can read here: [https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/](https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/)

I'm continuing to investigate, wanted to share fyi.

**Comment by bryanapellanes-okta** [comment] 2020-08-11 18:21
@mpbrooks93CAP,
Further internal review shows that this is related to the SameSite changes that the latest version of Chrome has introduced.

By default, the nonce cookie should be marked as secure if you are using https unless you have some sort of configuration or a proxy that is preventing this.

I suggest looking into the workarounds suggested by MS that should be done at the application level in the link posted in my previous comment also included here: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

I hope this helps.

**Comment by bryanapellanes-okta** [comment] 2020-08-11 18:24
@mpbrooks93CAP ,
Additional information from dotnet repo: [https://github.com/dotnet/aspnetcore/issues/19939](https://github.com/dotnet/aspnetcore/issues/19939)

**Comment by bryanapellanes-okta** [comment] 2020-08-11 20:08
Confirmed with support that issue was resolved.  Closing.

**Closed by bryanapellanes-okta** 2020-08-11 20:08 UTC
Labels: OKTA-312635, OKTA-318391

**Comment by brandongblack** [comment] 2020-08-18 15:36
@bryanapellanes-okta , I'm having this exact same issue with the latest version of Okta-asp-net and all of the latest dependencies. The issue is only affecting chrome. When you say that the issue is resolved I'm not seeing the same behavior

**Comment by bryanapellanes-okta** [comment] 2020-08-18 18:18
> @bryanapellanes-okta , I'm having this exact same issue with the latest version of Okta-asp-net and all of the latest dependencies. The issue is only affecting chrome. When you say that the issue is resolved I'm not seeing the same behavior

This is a breaking change that Chrome has introduced.  By default, the nonce cookie should be marked as secure if you are using https unless you have some sort of configuration or a proxy that is preventing this.
I suggest looking into the workarounds suggested by MS that should be done at the application level in the link posted in my previous comment also included here: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/
I hope this helps.

**Comment by bryanapellanes-okta** [comment] 2020-08-18 18:21
@brandongblack Please see response above.  Thanks!

**Comment by brandongblack** [comment] 2020-08-18 18:27
> > @bryanapellanes-okta , I'm having this exact same issue with the latest version of Okta-asp-net and all of the latest dependencies. The issue is only affecting chrome. When you say that the issue is resolved I'm not seeing the same behavior
> 
> This is a breaking change that Chrome has introduced. By default, the nonce cookie should be marked as secure if you are using https unless you have some sort of configuration or a proxy that is preventing this.
> I suggest looking into the workarounds suggested by MS that should be done at the application level in the link posted in my previous comment also included here: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/
> I hope this helps.

@bryanapellanes-okta thank you - will give this a try
